// remote-react2/src/App.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'

import './index.css'

const App = () => (
  <div className="container">
    <div>Name: remote-react2</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
)
const rootElement = document.getElementById('app')
if (!rootElement) throw new Error('Failed to find the root element')

const root = ReactDOM.createRoot(rootElement as HTMLElement)

root.render(<App />)

// remote-vue/src/App.vue
<template>
  <div class="container">
    <div>Name: remote-vue</div>
    <div>Framework: vue3</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
  <Counter />
</template>

<script lang="ts">
  import Counter from "./Counter.vue";

  export default {
    components: {
      Counter
    }
  }
</script>
